Feature/easy 48
Team-MoLU/E-DAY-Spring pull request #7
Opened 2024-05-25 14:23 UTC by Haneol

## 한 일
1. @id 어노테이션 사용 시 deprecated id() 경고 발생 수정.
2. Entity에서 List 타입 -> Set으로 변경
3. Task 엔티티 추가, TasksDTO 추가
4. TaskRepository, TaskController, TaskService 추가

## 할 일
1. 나머지 계획 세분화 기능 구현
2. 테스트 코드 작성 및 단위 테스트 진행
3. Entity <-> Dto 상호변환 공통코드 로직 적용 시, 해당 로직을 사용하도록 리팩토링 필요
4. JWT 기능 구현 완료 시, email을 @RequestParam 대신 Token에서 받아 사용하도록 리팩토링 필요

## 비고
- @yachae1101의 요청에 따라 빠르게 구현될 필요가 있는 기능 2개를 우선적으로 구현했음.

2024-05-27 08:07 UTC, yachae1101 requested changes
@GetMapping의 "a-task-detail/{taskId}" 를 수정된 API 설계에 맞게 변경 부탁드려요.

2024-05-31 12:10 UTC, Haneol commented
수정했습니다. 현재까지 추가된 API는 노션 API 문서에 체크해뒀습니다.
(READ 4개, CREATE 1개)

2024-06-01 11:36 UTC, Haneol commented
1. 이번 스프린트의 계획 세분화 기능 구현 완료 -> 노션 API 문서 참고
2. 테스트 코드 작성 및 단위 테스트 진행
@yachae1101

2024-06-01 23:25 UTC, yachae1101 approved these changes
확인했습니다.

2024-06-02 00:02 UTC, merged